#!/usr/bin/env python3
"""Generate (or verify) the fork's per-crate license clarifications (R8-P1-05).

The materialised TypeDB fork is one product shipping under ONE license, kept at
`fork/typedb/LICENSE`. Its workspace members carry no per-crate `license` field,
because upstream's Bazel-to-Cargo generation does not emit one, so `cargo deny`
reports every one of them as `unlicensed`.

The tempting fix is a blanket suppression. It is the wrong one: it would also
silence a genuinely unlicensed THIRD-PARTY crate, which is the finding this gate
exists to produce. So each internal crate is clarified INDIVIDUALLY, by name, to
the license the product ships under — and this tool keeps that list honest by
re-deriving it from `cargo metadata`:

    --check   the block in deny.toml must equal the derived one, or exit 1
    --write   regenerate the block in place

A crate that appears in the workspace and not in the list fails `--check`; a
crate in the list that has left the workspace fails it too. Neither can drift
into "we stopped noticing".
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
FORK = REPO / "fork" / "typedb"
DENY = FORK / "deny.toml"
LICENSE_FILE = FORK / "LICENSE"
EXPRESSION = "MPL-2.0"

BEGIN = "# --- generated by tools/fork/deny_clarify.py: do not hand-edit ---"
END = "# --- end generated block ---"


# The source-locked TypeDB git dependencies. They are TypeDB's own repositories,
# shipping under the same license as the product, and they carry no per-crate
# license field for the same reason the workspace members do not. They are
# listed by name here because `cargo metadata --no-deps` cannot see them, and
# their git identity is separately pinned by `[sources] allow-git` in deny.toml
# and re-derived by `tools/ci/check_dependency_sources.py`.
LOCKED_TYPEDB_GIT_CRATES = ("typedb-protocol", "typeql")


def workspace_members() -> list[str]:
    """Every crate this fork owns that carries no license field of its own."""
    proc = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--no-deps", "--offline"],
        capture_output=True,
        text=True,
        cwd=FORK,
    )
    if proc.returncode != 0:
        print(f"REFUSED: cargo metadata failed:\n{proc.stderr[-1500:]}", file=sys.stderr)
        raise SystemExit(1)
    meta = json.loads(proc.stdout)
    members = [
        p["name"] for p in meta["packages"] if not p.get("license") and not p.get("license_file")
    ]
    return sorted(set(members) | set(LOCKED_TYPEDB_GIT_CRATES))


def check_wildcards() -> int:
    """R8-P1-05: the surviving half of `wildcards = "deny"` on this workspace.

    cargo-deny's `allow-wildcard-paths` only applies to crates declaring
    `publish = false`, which upstream's generated manifests do not, so the fork
    policy sets `wildcards = "allow"`. The property that actually mattered is
    checked HERE instead, and checked exactly: a `*` requirement on a PATH
    dependency inside one workspace pins nothing the lockfile has not already
    pinned; a `*` on a REGISTRY dependency is an unpinned third party, and that
    is what this refuses.
    """
    proc = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--no-deps", "--offline"],
        capture_output=True,
        text=True,
        cwd=FORK,
    )
    if proc.returncode != 0:
        print(f"REFUSED: cargo metadata failed:\n{proc.stderr[-1500:]}", file=sys.stderr)
        return 1
    meta = json.loads(proc.stdout)
    # What ACTUALLY pins each name: the lockfile's source for it. A `*`
    # requirement on a crate the lock resolves from a git revision, or from a
    # path inside this workspace, is pinned by something stronger than a
    # version requirement. A `*` on a crates.io crate is not pinned at all,
    # and that is the whole hazard.
    lock = (FORK / "Cargo.lock").read_text()
    sources: dict[str, str] = {}
    name = None
    for line in lock.splitlines():
        if line.startswith("name = "):
            name = line.split("=", 1)[1].strip().strip('"')
        elif line.startswith("source = ") and name:
            sources[name] = line.split("=", 1)[1].strip().strip('"')
    offenders, pinned = [], {"path": 0, "git": 0}
    for package in meta["packages"]:
        for dep in package.get("dependencies") or []:
            if dep.get("req") not in ("*", "^*"):
                continue
            if dep.get("path"):
                pinned["path"] += 1
                continue
            source = sources.get(dep["name"], "")
            if source.startswith("git+"):
                pinned["git"] += 1
                continue
            offenders.append(
                f"{package['name']} -> {dep['name']} (req {dep['req']!r}, resolved from "
                f"{source or '<no lock entry>'})"
            )
    if offenders:
        print(
            "DENY WILDCARDS: FAIL - a REGISTRY dependency carries a wildcard requirement",
            file=sys.stderr,
        )
        for o in offenders:
            print(f"  - {o}", file=sys.stderr)
        return 1
    print(
        f"DENY WILDCARDS: PASS ({pinned['path']} wildcard(s) on path dependencies inside this "
        f"workspace, {pinned['git']} on source-locked git revisions, 0 on unpinned registry crates)"
    )
    return 0


def render(members: list[str]) -> str:
    lines = [
        BEGIN,
        f"# {len(members)} workspace members of the materialised TypeDB fork. They carry no",
        "# per-crate license field (upstream's Bazel-to-Cargo generation emits none); the",
        f"# product's license is {FORK.relative_to(REPO)}/LICENSE. Each is clarified BY NAME so a",
        "# genuinely unlicensed third-party crate still fails this gate.",
    ]
    for name in members:
        lines += [
            "",
            "[[licenses.clarify]]",
            f'crate = "{name}"',
            f'expression = "{EXPRESSION}"',
            "license-files = []",
        ]
    lines += ["", END]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument(
        "--check-wildcards",
        action="store_true",
        help="every wildcard requirement must be a PATH dependency, never a registry one",
    )
    args = ap.parse_args()

    if args.check_wildcards:
        return check_wildcards()

    if not LICENSE_FILE.is_file():
        print(
            f"REFUSED: {LICENSE_FILE.relative_to(REPO)} is absent. Clarifying ~40 crates to "
            f"{EXPRESSION} is only honest while the product's own license file says so.",
            file=sys.stderr,
        )
        return 1

    members = workspace_members()
    block = render(members)
    text = DENY.read_text()
    existing = re.search(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", text, re.S)

    if args.write:
        new = (
            (text[: existing.start()] + block + text[existing.end() :])
            if existing
            else (text.rstrip("\n") + "\n\n" + block)
        )
        DENY.write_text(new)
        print(f"{DENY.relative_to(REPO)}: clarified {len(members)} internal crates")
        return 0

    if existing is None:
        print(
            f"DENY CLARIFY: FAIL - {DENY.relative_to(REPO)} has no generated block", file=sys.stderr
        )
        return 1
    if existing.group(0) != block:
        have = set(re.findall(r'crate = "([^"]+)"', existing.group(0)))
        want = set(members)
        print("DENY CLARIFY: FAIL - the clarification block has drifted from the workspace")
        for name in sorted(want - have):
            print(f"  MISSING  {name} is a workspace member with no license and no clarification")
        for name in sorted(have - want):
            print(f"  STALE    {name} is clarified but is no longer an unlicensed workspace member")
        return 1
    print(
        f"DENY CLARIFY: PASS ({len(members)} internal crates clarified, none missing, none stale)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
