#!/usr/bin/env python3
"""R6-PORT-01 - the four source postures, executed, not asserted.

The audit's finding was posture-shaped: everything passed in a git checkout
and two controls failed in a `git archive` materialisation. A fix that is only
tested in a checkout would be the same defect with a different name, so this
self-test MATERIALISES each posture for real and resolves the identity in it:

  1. git checkout            - a real clone of this repository
  2. git archive             - `git archive HEAD | tar -x` (no .git; git's
                               export-subst expands the identity file)
  3. release tarball         - identity generated by --generate, then tarred
                               and untarred; identity_digest re-verified
  4. installed package       - a subtree copy with the identity file, no .git
  5. naked copy (negative)   - a checkout copied WITHOUT .git and WITHOUT an
                               expanded identity: must REFUSE, not guess
  6. tampered identity (neg) - the digest-bound identity edited after signing:
                               must REFUSE

Both resolvers are exercised in every posture - the Python one and the
TypeScript one probes call - because a fix that only holds in one language is
not a fix for a repository that runs both.

Usage: python3 tools/release/release_identity_selftest.py
Exit codes: 0 all postures behaved as specified, 1 otherwise.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

from release_identity import (  # noqa: E402
    IDENTITY_FILENAME,
    SourceIdentityUnavailable,
    canonical_digest,
    generate,
    resolve,
)

TS_RESOLVER = HERE / "release-identity.mts"
NODE = ["node", "--experimental-strip-types", "--no-warnings"]


def ts_resolve(root: Path) -> tuple[dict | None, str | None]:
    """Run the TypeScript resolver in `root`; return (identity, error-code)."""
    script = f"""
import {{ resolveReleaseIdentity, SourceIdentityUnavailable }} from {json.dumps(str(TS_RESOLVER))};
try {{
  process.stdout.write(JSON.stringify({{ ok: true, identity: resolveReleaseIdentity({json.dumps(str(root))}) }}));
}} catch (err) {{
  const code = err instanceof SourceIdentityUnavailable ? err.code : "UNEXPECTED";
  process.stdout.write(JSON.stringify({{ ok: false, code, message: String(err && err.message) }}));
}}
"""
    entry = root / ".release-identity-probe.mts"
    entry.write_text(script, encoding="utf-8")
    try:
        proc = subprocess.run([*NODE, str(entry)], capture_output=True, text=True, cwd=str(root))
    finally:
        entry.unlink(missing_ok=True)
    if proc.returncode != 0 or not proc.stdout.strip():
        return None, f"node failed ({proc.returncode}): {proc.stderr.strip()[:400]}"
    out = json.loads(proc.stdout)
    return (out["identity"], None) if out["ok"] else (None, out["code"])


def make_checkout(tmp: Path) -> Path:
    """A real, disposable clone of this repository.

    The two files that make the archive posture work - RELEASE-IDENTITY.json
    and .gitattributes - are synced from the WORKING TREE and committed in the
    throwaway clone before anything is exported. That keeps this self-test
    honest while the change is still uncommitted (it exercises the files as
    they are now, not as HEAD happens to have them) and becomes a no-op commit
    once they are committed upstream.
    """
    dst = tmp / "checkout"
    subprocess.run(
        [
            "git",
            "clone",
            "--quiet",
            "--no-hardlinks",
            "--depth",
            "1",
            "--no-local",
            str(REPO_ROOT),
            str(dst),
        ],
        check=True,
        capture_output=True,
    )
    for name in (IDENTITY_FILENAME, ".gitattributes"):
        src = REPO_ROOT / name
        if src.exists():
            shutil.copy2(src, dst / name)
    subprocess.run(
        ["git", "-C", str(dst), "add", "--", IDENTITY_FILENAME, ".gitattributes"],
        check=True,
        capture_output=True,
    )
    staged = subprocess.run(
        ["git", "-C", str(dst), "diff", "--cached", "--quiet"], capture_output=True
    )
    if staged.returncode != 0:
        subprocess.run(
            [
                "git",
                "-C",
                str(dst),
                "-c",
                "user.email=selftest@local",
                "-c",
                "user.name=selftest",
                "commit",
                "--quiet",
                "-m",
                "release-identity self-test: sync working-tree identity files",
            ],
            check=True,
            capture_output=True,
        )
    return dst


# The postures are exercised over a REPRESENTATIVE SUBTREE (the identity file
# plus tools/release), not the whole repository. That is not a shortcut for
# convenience: this repository carries ~700 MB of archived evidence logs, and
# copying them six times to test a resolver would make the self-test fail for
# want of disk rather than for want of correctness - which it did, once, before
# this was narrowed. Everything the resolver reads is inside the subtree, the
# archive is a REAL `git archive` of REAL committed bytes (so export-subst is
# genuinely exercised through the real .gitattributes), and the negative
# postures are the same subtree with the identity removed or altered.
ARCHIVE_PATHS = ["RELEASE-IDENTITY.json", ".gitattributes", "tools/release"]


def make_archive(tmp: Path, source: Path) -> Path:
    dst = tmp / "archive"
    dst.mkdir()
    tar_path = tmp / "archive.tar"
    with tar_path.open("wb") as fh:
        subprocess.run(
            ["git", "-C", str(source), "archive", "HEAD", "--", *ARCHIVE_PATHS],
            stdout=fh,
            check=True,
        )
    with tarfile.open(tar_path) as tf:
        tf.extractall(dst)  # noqa: S202 - our own archive, produced two lines above
    return dst


def _subtree_copy(source: Path, dst: Path) -> Path:
    """The same paths `git archive` exports, copied WITHOUT .git."""
    dst.mkdir(parents=True, exist_ok=True)
    for rel in ARCHIVE_PATHS:
        src = source / rel
        if not src.exists():
            continue
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, target, ignore=shutil.ignore_patterns("__pycache__"))
        else:
            shutil.copy2(src, target)
    return dst


def make_release_tarball(tmp: Path, source: Path) -> Path:
    staged = _subtree_copy(source, tmp / "release-stage")
    generate(source, staged)  # identity generated FROM the checkout, INTO the artifact
    tar_path = tmp / "release.tar"
    with tarfile.open(tar_path, "w") as tf:
        tf.add(staged, arcname=".")
    dst = tmp / "release"
    dst.mkdir()
    with tarfile.open(tar_path) as tf:
        tf.extractall(dst)  # noqa: S202
    return dst


def make_installed(tmp: Path, release: Path) -> Path:
    """An 'installed package': a few files plus the identity, no .git, no tree."""
    dst = tmp / "installed"
    dst.mkdir()
    shutil.copy2(release / IDENTITY_FILENAME, dst / IDENTITY_FILENAME)
    (dst / "bin").mkdir()
    (dst / "bin" / "placeholder").write_text("installed payload\n", encoding="utf-8")
    return dst


def make_naked_copy(tmp: Path, source: Path) -> Path:
    """A checkout COPIED rather than exported: no .git, and the identity file
    still carries its literal $Format: placeholders because nothing expanded
    them. This is the posture that must REFUSE."""
    return _subtree_copy(source, tmp / "naked")


def make_tampered(tmp: Path, release: Path) -> Path:
    dst = tmp / "tampered"
    shutil.copytree(release, dst)
    body = json.loads((dst / IDENTITY_FILENAME).read_text(encoding="utf-8"))
    body["release_commit"] = "0" * 40  # a different commit, digest untouched
    (dst / IDENTITY_FILENAME).write_text(json.dumps(body, indent=2), encoding="utf-8")
    return dst


def main() -> int:
    failures = 0
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        checkout = make_checkout(tmp)
        head = subprocess.run(
            ["git", "-C", str(checkout), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()

        archive = make_archive(tmp, checkout)
        release = make_release_tarball(tmp, checkout)
        installed = make_installed(tmp, release)
        naked = make_naked_copy(tmp, checkout)
        tampered = make_tampered(tmp, release)

        cases = [
            ("1 git checkout", checkout, head, "git-checkout", True),
            (
                "2 git archive (no .git; export-subst expanded)",
                archive,
                head,
                "git-archive-export-subst",
                False,
            ),
            (
                "3 release tarball (generated + digest-bound)",
                release,
                head,
                "release-artifact",
                True,
            ),
            ("4 installed package (identity file only)", installed, head, "release-artifact", True),
            ("5 NEGATIVE naked copy without .git or an expanded identity", naked, None, None, None),
            ("6 NEGATIVE identity edited after it was digest-bound", tampered, None, None, None),
        ]

        for name, root, want_commit, want_posture, want_verified in cases:
            # --- python resolver ---
            try:
                got = resolve(root)
                py_err = None
            except SourceIdentityUnavailable as exc:
                got, py_err = None, str(exc)
            if want_commit is None:
                ok_py = py_err is not None
                why = f"expected SOURCE_IDENTITY_UNAVAILABLE, resolved {got}"
            else:
                ok_py = (
                    py_err is None
                    and got["release_commit"] == want_commit
                    and got["posture"] == want_posture
                    and got["verified"] is want_verified
                )
                why = f"expected {want_commit[:12]}/{want_posture}/verified={want_verified}, got {got or py_err}"
            print(f"  {'ok  ' if ok_py else 'FAIL'} py  {name}")
            if not ok_py:
                print(f"        {why}")
                failures += 1

            # --- typescript resolver (the one probes call) ---
            ts_ident, ts_err = ts_resolve(root)
            if want_commit is None:
                ok_ts = ts_err == "SOURCE_IDENTITY_UNAVAILABLE"
                why = f"expected SOURCE_IDENTITY_UNAVAILABLE, got {ts_err or ts_ident}"
            else:
                ok_ts = (
                    ts_err is None
                    and ts_ident["releaseCommit"] == want_commit
                    and ts_ident["posture"] == want_posture
                    and ts_ident["verified"] is want_verified
                )
                why = f"expected {want_commit[:12]}/{want_posture}/verified={want_verified}, got {ts_ident or ts_err}"
            print(f"  {'ok  ' if ok_ts else 'FAIL'} ts  {name}")
            if not ok_ts:
                print(f"        {why}")
                failures += 1

        # The digest must actually bind: recomputing it over the tampered body
        # must differ from the recorded one (otherwise case 6 passes vacuously).
        body = json.loads((tampered / IDENTITY_FILENAME).read_text(encoding="utf-8"))
        if canonical_digest(body) == body["identity_digest"]:
            print("  FAIL     the identity digest does not actually cover release_commit")
            failures += 1
        else:
            print("  ok       the identity digest demonstrably covers release_commit")

    print()
    if failures:
        print(f"release-identity posture self-test: {failures} check(s) FAILED")
        return 1
    print(
        "release-identity posture self-test: all 6 postures behaved as specified, in both resolvers"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
