//! Generation of the upstream test denominator (brief §22.2, Appendix E.1).
//!
//! The catalogue is built from three independent readings of the pinned checkout and
//! then reconciled, because no single reading is trustworthy on its own:
//!
//! 1. `cargo metadata` — but the pinned root `Cargo.toml` is generated by a
//!    Bazel-invoking sync tool ("Do not modify this file", L1-2), so Cargo can silently
//!    omit targets that BUILD declares.
//! 2. The BUILD files — parsed directly, so a target that never reached Cargo is still
//!    counted.
//! 3. The composite corpora — behaviour scenarios and the failpoint registry — whose leaf
//!    cases live outside both of the above.
//!
//! Any target present on one side and missing on the other is a reconciliation finding,
//! never a silent drop.

pub mod cargo_meta;
pub mod failpoints;
pub mod gherkin;
pub mod model;
pub mod starlark;

use std::{
    collections::{BTreeMap, BTreeSet},
    path::Path,
};

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use model::*;

/// A BUILD-declared test target, before reconciliation with Cargo.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildTestTarget {
    /// Bazel label, e.g. `//tests/behaviour/connection:test_connection`.
    pub label: String,
    pub rule: String,
    /// BUILD file path relative to the fork root, plus the line of the rule call.
    pub build_file: String,
    pub line: usize,
    /// `crate = ":storage"` marks a crate-unit wrapper -> `cargo test --lib -p storage`.
    pub crate_under_test: Option<String>,
    pub crate_root: Option<String>,
    pub srcs: Vec<String>,
    pub data: Vec<String>,
    pub env: BTreeMap<String, String>,
    pub crate_features: Vec<String>,
    pub tags: Vec<String>,
    /// Attributes not modelled above, kept verbatim so nothing is lost silently.
    #[serde(default)]
    pub other_attrs: BTreeMap<String, Vec<String>>,
}

impl BuildTestTarget {
    /// One-line description of the unmodelled attributes, for evidence readability.
    pub fn attr_summary(&self) -> String {
        self.other_attrs
            .iter()
            .map(|(k, v)| format!("{k}={}", v.join("|")))
            .collect::<Vec<_>>()
            .join(" ")
    }
}

/// What the three readings agreed and disagreed about.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Reconciliation {
    /// Cargo test targets with no corresponding BUILD `rust_test` that are not explained
    /// by the lib-unit rule below. Non-empty means the two readings genuinely disagree.
    pub cargo_only: Vec<String>,
    /// Lib targets Cargo will run `#[test]`s for even though upstream's BUILD declares no
    /// `rust_test(crate = …)` wrapper. This is extra coverage, not a hole — recorded so the
    /// superset is visible rather than discovered later as a surprise.
    pub cargo_only_lib_units: Vec<String>,
    /// For each Cargo-only target, what upstream declares for the same sources. Without
    /// this the list is just names, and "Cargo runs a test Bazel does not" reads the same
    /// as "the reconciler failed to match a pair".
    pub cargo_only_explained: BTreeMap<String, String>,
    /// Every name declared by any BUILD rule, test-producing or not, as
    /// `name -> "<rule> at <file>"`. This is what lets a Cargo-only target be explained
    /// rather than merely listed.
    #[serde(skip_serializing)]
    pub declared_names: BTreeMap<String, String>,
    /// `srcs` of every rule, keyed by Bazel label. A `rustfmt_test` names the *targets* it
    /// formats rather than files, so resolving it needs the sources of ordinary
    /// `rust_library`/`rust_binary` rules that are not themselves test producers.
    #[serde(skip_serializing)]
    pub rule_srcs: BTreeMap<String, Vec<String>>,
    /// BUILD `rust_test` targets with no corresponding Cargo target.
    pub build_only: Vec<String>,
    /// Matched on both sides.
    pub matched: Vec<String>,
    /// Rule names encountered that are not known test producers or known non-test rules.
    pub unknown_rules: Vec<String>,
    /// BUILD files this tool could not parse. Non-empty means the catalogue is not final.
    pub unparsed_build_files: Vec<String>,
}

fn sha256_file(path: &Path) -> Result<String> {
    let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    Ok(hex::encode(Sha256::digest(&bytes)))
}

fn sha256_str(s: &str) -> String {
    hex::encode(Sha256::digest(s.as_bytes()))
}

/// Rules in TypeDB's BUILD files verified to produce no test target.
///
/// Membership here is a claim about upstream source, so each entry was read rather than
/// assumed. The non-obvious one is `rust_tonic_compile`
/// (`typedb/dependencies @ a5c51254` `builder/proto_grpc/rust/compile.bzl` L30-46): it is
/// `rule(implementation = _rust_tonic_compile_impl, …)` returning `DefaultInfo`, with
/// `test` unset — a code generator, not a test. Anything not listed here fails G0 rather
/// than being skipped, which is what makes "zero unknown macro" mean something.
const KNOWN_NON_TEST_RULES: [&str; 32] = [
    "load",
    "package",
    "exports_files",
    "filegroup",
    "rust_library",
    "rust_binary",
    "genrule",
    "alias",
    "config_setting",
    "assemble_apt",
    "pkg_files",
    "licenses",
    "platform",
    "string_flag",
    "proto_library",
    "rust_tonic_compile",
    // Packaging/deployment macros from typedb/bazel-distribution @ ab5bfc90. Each was read:
    // apt/rules.bzl, artifact/rules.bzl, brew/rules.bzl and common/rules.bzl contain no
    // `test = True` rule and expand to no `*_test` target.
    "deploy_apt",
    "deploy_artifact",
    "deploy_brew",
    "keychain_setup",
    "mac_pkg_installer",
    "package_version_vars",
    "artifact_repackage",
    "pkg_attributes",
    // Standard external rules: bazel_skylib, rules_oci, rules_pkg, and Bazel natives.
    "label_flag",
    "select_file",
    "oci_image",
    "oci_push",
    "pkg_filegroup",
    "pkg_tar",
    "pkg_zip",
    "constraint_linux_arm64",
];

/// Read every BUILD file under `fork_root` and extract its test targets.
///
/// Returns the targets plus a reconciliation record carrying anything unrecognised —
/// an unknown rule or an unparseable file must fail G0, so it is surfaced, not dropped.
pub fn scan_build_files(fork_root: &Path) -> Result<(Vec<BuildTestTarget>, Reconciliation)> {
    let mut targets = Vec::new();
    let mut recon = Reconciliation::default();
    let mut unknown = BTreeSet::new();

    let mut build_files: Vec<_> = walkdir::WalkDir::new(fork_root)
        .into_iter()
        // `bazel-typedb/` is the runfiles tree the runner stages, not upstream source. The
        // behaviour corpus inside it carries 12 BUILD files of its own, and scanning them
        // after a run has staged the fixture produced 157 static targets against a
        // catalogue of 156 — the denominator silently depending on whether a run had
        // happened yet.
        .filter_entry(|e| e.file_name() != "bazel-typedb" && e.file_name() != ".git")
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file() && e.file_name() == "BUILD")
        .map(|e| e.path().to_path_buf())
        .collect();
    build_files.sort();

    for path in build_files {
        let rel = path
            .strip_prefix(fork_root)?
            .to_string_lossy()
            .replace('\\', "/");
        let pkg = rel.trim_end_matches("BUILD").trim_end_matches('/').to_string();
        let text = std::fs::read_to_string(&path)?;

        let calls = match starlark::parse_build_file(&text) {
            Ok(c) => c,
            Err(e) => {
                recon.unparsed_build_files.push(format!("{rel}: {e}"));
                continue;
            }
        };

        for call in calls {
            if let Some(name) = call.name() {
                recon
                    .declared_names
                    .entry(name.to_string())
                    .or_insert_with(|| format!("{} at {rel}", call.rule));
                // Sources are package-relative in BUILD; store them workspace-relative.
                let srcs: Vec<String> = call
                    .attr_strings("srcs")
                    .into_iter()
                    .map(|s| if pkg.is_empty() { s.to_string() } else { format!("{pkg}/{s}") })
                    .collect();
                if !srcs.is_empty() {
                    recon.rule_srcs.insert(format!("//{pkg}:{name}"), srcs);
                }
            }
            if !starlark::TEST_PRODUCING_RULES.contains(&call.rule.as_str()) {
                if !KNOWN_NON_TEST_RULES.contains(&call.rule.as_str()) {
                    unknown.insert(format!("{}: {} (line {})", rel, call.rule, call.line));
                }
                continue;
            }
            let Some(name) = call.name() else {
                bail!("{rel}:{}: {} has no name attribute", call.line, call.rule);
            };

            let mut env = BTreeMap::new();
            if let Some(value) = call.attrs.get("env") {
                collect_env(value, &mut env);
            }

            targets.push(BuildTestTarget {
                label: format!("//{pkg}:{name}"),
                rule: call.rule.clone(),
                build_file: rel.clone(),
                line: call.line,
                crate_under_test: call
                    .attrs
                    .get("crate")
                    .and_then(starlark::Value::as_str)
                    .map(|s| s.trim_start_matches(':').to_string()),
                crate_root: call
                    .attrs
                    .get("crate_root")
                    .and_then(starlark::Value::as_str)
                    .map(str::to_string),
                srcs: call.attr_strings("srcs").into_iter().map(str::to_string).collect(),
                data: call.attr_strings("data").into_iter().map(str::to_string).collect(),
                env,
                crate_features: call
                    .attr_strings("crate_features")
                    .into_iter()
                    .map(str::to_string)
                    .collect(),
                tags: call.attr_strings("tags").into_iter().map(str::to_string).collect(),
                other_attrs: call
                    .attrs
                    .iter()
                    .filter(|(k, _)| {
                        !matches!(
                            k.as_str(),
                            "name" | "crate" | "crate_root" | "srcs" | "data" | "env"
                                | "crate_features" | "tags" | "deps"
                        )
                    })
                    .map(|(k, v)| {
                        (k.clone(), v.strings().into_iter().map(str::to_string).collect())
                    })
                    .collect(),
            });
        }
    }

    recon.unknown_rules = unknown.into_iter().collect();
    Ok((targets, recon))
}

/// Flatten an `env = {...}` or `env = select({...})` attribute into key/value pairs.
///
/// Every `select` branch is kept: the archive path differs per platform and the
/// catalogue must record the whole predicate space, not the host's branch.
fn collect_env(value: &starlark::Value, out: &mut BTreeMap<String, String>) {
    match value {
        starlark::Value::Dict(pairs) => {
            for (k, v) in pairs {
                match (k.as_str(), v) {
                    (Some(key), starlark::Value::Str(val)) => {
                        out.insert(key.to_string(), val.clone());
                    }
                    // A select() maps configuration labels to nested env dicts.
                    (_, nested) => collect_env(nested, out),
                }
            }
        }
        starlark::Value::Call { args, kwargs, .. } => {
            args.iter().for_each(|a| collect_env(a, out));
            kwargs.values().for_each(|a| collect_env(a, out));
        }
        starlark::Value::List(items) => items.iter().for_each(|i| collect_env(i, out)),
        _ => {}
    }
}

/// Inputs for one catalogue generation run.
pub struct CatalogInputs<'a> {
    /// Root of the TypeDB checkout being catalogued.
    pub fork_root: &'a Path,
    /// Root of the pinned `typedb-behaviour` corpus.
    pub behaviour_root: &'a Path,
    pub source_lock_digest: String,
    /// Digest of the resolved native toolchain, or `None` while the `NATIVE` node is open.
    pub native_toolchain_digest: Option<String>,
    pub rustc: String,
    pub cargo: String,
    pub target_triple: String,
    pub cargo_bin: String,
    /// Extra `PATH` entries needed by build scripts (e.g. the pinned `protoc`).
    pub extra_path: Option<String>,
}

/// Everything the generator learned, including the parts that do not fit the schema.
pub struct CatalogOutput {
    pub catalog: Catalog,
    pub reconciliation: Reconciliation,
    pub build_targets: Vec<BuildTestTarget>,
}

/// Which behaviour feature files a target consumes, derived from its BUILD `data`.
fn feature_paths_from_data(data: &[String]) -> Vec<String> {
    data.iter()
        .filter_map(|d| d.strip_prefix("@typedb_behaviour//"))
        .map(|rest| rest.replacen(':', "/", 1))
        .collect()
}

/// Feature files a target's own sources actually open.
///
/// Bazel `data` says what is *available* to a target, not what it runs. `test_query`
/// declares `@typedb_behaviour//query/functions:negation.feature` as data, but no Rust entry
/// point references it — `tests/behaviour/query/functions/` has basic, definition, recursion,
/// signature, structure and usage, and no `negation.rs`. Upstream marks that feature
/// `# TODO: Port to 3.0` at L5. Counting it from `data` put six scenarios in the denominator
/// that nothing can ever execute.
///
/// The paths are read from `Context::test("…")` string literals instead, which is what
/// decides execution. Everything after the corpus root is kept, so both the `../` and
/// `bazel-typedb/external/` spellings — and the two misspellings of CR-A-08 — resolve to the
/// same corpus-relative path.
fn feature_paths_from_sources(fork_root: &Path, src_files: &[String]) -> Result<Vec<String>> {
    let mut out = BTreeSet::new();
    for rel in src_files {
        let path = fork_root.join(rel);
        let Ok(text) = std::fs::read_to_string(&path) else { continue };
        for literal in text.split('"').skip(1).step_by(2) {
            if !literal.ends_with(".feature") {
                continue;
            }
            // Strip whichever corpus-root spelling precedes the corpus-relative part.
            let Some(idx) = literal.find("typedb_behaviour") else { continue };
            let after = &literal[idx..];
            let Some(slash) = after.find('/') else { continue };
            out.insert(after[slash + 1..].to_string());
        }
    }
    Ok(out.into_iter().collect())
}

pub fn generate(inputs: &CatalogInputs<'_>) -> Result<CatalogOutput> {
    let meta = cargo_meta::load(inputs.fork_root, &inputs.cargo_bin, inputs.extra_path.as_deref())?;
    let (build_targets, mut recon) = scan_build_files(inputs.fork_root)?;

    let mut targets: Vec<Target> = Vec::new();
    let mut leaf_cases: Vec<LeafCase> = Vec::new();
    let mut fixtures: Vec<Fixture> = Vec::new();
    let mut exclusions: Vec<Exclusion> = Vec::new();

    // --- Behaviour corpus: parsed once, indexed by feature path.
    // The corpus is parsed once per harness, because the two disagree about which tags
    // suppress a scenario (see `gherkin::Harness`). A single parse would either count
    // `@ignore-typedb-http` scenarios as runnable under HTTP targets — they showed up as
    // never-executed — or mark them ignored under native targets, which do run them.
    let scenarios_native = gherkin::parse_corpus_for(gherkin::Harness::Native, inputs.behaviour_root)?;
    let scenarios_http = gherkin::parse_corpus_for(gherkin::Harness::Http, inputs.behaviour_root)?;
    let mut by_feature_http: BTreeMap<String, Vec<&gherkin::Scenario>> = BTreeMap::new();
    for s in &scenarios_http {
        by_feature_http.entry(s.feature_path.clone()).or_default().push(s);
    }
    let scenarios = scenarios_native;
    let mut by_feature: BTreeMap<String, Vec<&gherkin::Scenario>> = BTreeMap::new();
    for s in &scenarios {
        by_feature.entry(s.feature_path.clone()).or_default().push(s);
    }

    // The whole corpus is one staged fixture; its digest is the scenario denominator's anchor.
    let (behaviour_digest, _, _) = source_lock::hash_tree(inputs.behaviour_root)?;
    fixtures.push(Fixture {
        fixture_id: "typedb-behaviour".into(),
        kind: FixtureKind::Directory,
        source: Some("typedb/typedb-behaviour @ ac5d5733a484cea1d8809a2968029a818fdae24f".into()),
        sha256: behaviour_digest,
        licence: "MPL-2.0".into(),
        // Upstream's Cargo path expects Bazel's external symlink farm; the runner stages
        // the corpus there so the test sources stay byte-identical (brief §22.5).
        destination: Some("bazel-typedb/external/typedb_behaviour+".into()),
    });

    // --- Index BUILD targets for reconciliation, two ways.
    //
    // Integration tests match on target name. Crate-unit wrappers do not: Bazel writes
    // `rust_test(name = "test_crate_storage", crate = ":storage")`, which is the *lib*
    // target of package `storage` under Cargo. Matching only on name would report every
    // lib harness as "Cargo-only" and hide 30-odd genuine matches.
    let mut build_by_name: BTreeMap<&str, &BuildTestTarget> = BTreeMap::new();
    // Crate-unit wrappers are keyed by the BUILD file's directory, not by crate name:
    // `admin/client/BUILD` declares `rust_test(crate = ":client")` while the Cargo package
    // there is named `typedb-admin`. Matching on names would leave that pair unreconciled.
    let mut build_by_dir: BTreeMap<String, &BuildTestTarget> = BTreeMap::new();
    for bt in &build_targets {
        if bt.rule != "rust_test" {
            continue;
        }
        let name = bt.label.rsplit(':').next().unwrap_or_default();
        build_by_name.insert(name, bt);
        if bt.crate_under_test.is_some() {
            let dir = bt.build_file.trim_end_matches("BUILD").trim_end_matches('/').to_string();
            build_by_dir.insert(dir, bt);
        }
    }

    let mut matched_build: BTreeSet<String> = BTreeSet::new();

    // --- Cargo test-capable targets.
    for (pkg, target) in cargo_meta::test_capable_targets(&meta) {
        let src_rel = target
            .src_path
            .strip_prefix(inputs.fork_root)
            .unwrap_or(&target.src_path)
            .to_string_lossy()
            .replace('\\', "/");
        // The kind is part of the id because the schema is closed and the runner must know
        // which Cargo selector to use: `--lib`, `--bin`, `--test` or `--bench` are not
        // interchangeable, and picking the wrong one fails as "no such target".
        let kind = target.kind.first().map(String::as_str).unwrap_or("unknown");
        let target_id = format!("cargo::{kind}::{}::{}", pkg.name, target.name);

        let package_dir = pkg
            .manifest_path
            .parent()
            .and_then(|p| p.strip_prefix(inputs.fork_root).ok())
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .unwrap_or_default();
        let build_target = build_by_name
            .get(target.name.as_str())
            .copied()
            .or_else(|| target.is_lib().then(|| build_by_dir.get(&package_dir).copied()).flatten());
        if let Some(bt) = build_target {
            matched_build.insert(bt.label.clone());
        }

        // Every `.rs` file the harness compiles, hashed, so a source edit is visible.
        let mut source_files = vec![HashedFile {
            path: src_rel.clone(),
            sha256: sha256_file(&target.src_path)?,
        }];
        if let Some(dir) = target.src_path.parent() {
            let mut siblings: Vec<_> = walkdir::WalkDir::new(dir)
                .max_depth(4)
                .into_iter()
                .filter_map(Result::ok)
                .filter(|e| e.file_type().is_file())
                .filter(|e| e.path().extension().is_some_and(|x| x == "rs"))
                .filter(|e| e.path() != target.src_path)
                .map(|e| e.path().to_path_buf())
                .collect();
            siblings.sort();
            for s in siblings {
                source_files.push(HashedFile {
                    path: s
                        .strip_prefix(inputs.fork_root)
                        .unwrap_or(&s)
                        .to_string_lossy()
                        .replace('\\', "/"),
                    sha256: sha256_file(&s)?,
                });
            }
        }

        // `bazel` is a Bazel-only crate feature: no Cargo manifest declares it, so passing
        // it makes cargo fail with "does not contain this feature" and the target reports
        // zero cases. It is also exactly the feature that must stay *off* here — upstream
        // gates the fixture path on it (`tests/behaviour/connection/database.rs` L17-23),
        // and the Cargo lane deliberately takes the non-Bazel branch, which is why the
        // runner stages the corpus under `bazel-typedb/external/`. See CR-A-03.
        //
        // The BUILD declaration is not lost: `build-test-targets.json` records it verbatim.
        let features: Vec<String> = build_target
            .map(|b| b.crate_features.iter().filter(|f| *f != "bazel").cloned().collect())
            .unwrap_or_default();
        let data = build_target.map(|b| b.data.clone()).unwrap_or_default();
        // Intersect the two readings: `data` is what Bazel makes available to this target,
        // the sources are what some file in its tree actually opens. Neither alone is right.
        //
        // `data` alone counts `query/functions/negation.feature` for `test_query` — declared
        // available, but no Rust entry point references it (there is no `negation.rs`, and
        // upstream marks the feature `# TODO: Port to 3.0` at L5), so six scenarios sat in
        // the denominator that nothing could execute. Sources alone over-collect, because
        // `source_files` deliberately includes sibling modules for hashing and those belong
        // to neighbouring targets — it inflated the Cucumber count from 4164 to 5052.
        //
        // Available AND opened is the set a target can actually run.
        let src_rels: Vec<String> = source_files.iter().map(|f| f.path.clone()).collect();
        let from_sources = feature_paths_from_sources(inputs.fork_root, &src_rels)?;
        let from_data = feature_paths_from_data(&data);
        let feature_files: Vec<String> = if from_sources.is_empty() {
            from_data
        } else {
            let opened: BTreeSet<&str> = from_sources.iter().map(String::as_str).collect();
            from_data.into_iter().filter(|d| opened.contains(d.as_str())).collect()
        };
        let env: BTreeMap<String, String> =
            build_target.map(|b| b.env.clone()).unwrap_or_default();

        // Classify how this target discovers its leaf cases.
        let is_behaviour = !feature_files.is_empty();
        let is_failpoint = target.name == "test_fail_points";
        // Upstream benches set `harness = false` (criterion), e.g. `concept/Cargo.toml`
        // L104-106. Such a binary has no libtest `--list`, so its cases cannot be
        // enumerated; it is one script-shaped leaf case that must run to completion.
        let is_bench = target.is_bench();
        let case_discovery = if is_failpoint {
            CaseDiscovery::FailpointRegistry
        } else if is_behaviour {
            CaseDiscovery::CucumberScenarios
        } else if is_bench {
            CaseDiscovery::Script
        } else {
            CaseDiscovery::LibtestList
        };

        // A target whose fixtures Bazel used to wire is launcher-adapted: the runner
        // stages archive/env/cwd externally and the sources stay byte-identical.
        let port_status = if is_behaviour || is_failpoint || is_bench || !env.is_empty() {
            PortStatus::LauncherAdapted
        } else {
            PortStatus::ByteIdentical
        };

        let mut fixture_ids = Vec::new();
        if is_behaviour {
            fixture_ids.push("typedb-behaviour".to_string());
        }
        if is_failpoint || target.name == "test_assembly" {
            fixture_ids.push("typedb-assembly-archive".to_string());
            fixture_ids.push("typedb-console".to_string());
        }

        targets.push(Target {
            target_id: target_id.clone(),
            origin: Origin::Cargo,
            upstream_label: build_target.map(|b| b.label.clone()),
            cargo_package: Some(pkg.name.clone()),
            cargo_target: Some(target.name.clone()),
            source_files,
            case_discovery,
            // No upstream Cargo target is host-restricted; Bazel's `select` on the assembly
            // archive is a fixture selector, not a platform gate.
            platform_predicate: "linux-x86_64".into(),
            features,
            cfg: Vec::new(),
            env,
            fixture_ids,
            working_directory: Some(".".into()),
            // Behaviour and assembly suites boot real servers; unit targets are quick.
            timeout_seconds: if is_behaviour || is_failpoint { 3600 } else { 900 },
            serial_group: (is_behaviour || is_failpoint)
                .then(|| "server-port".to_string()),
            port_status,
        });

        // --- Leaf cases.
        if is_behaviour {
            for feature in &feature_files {
                // HTTP driver targets live under tests/behaviour/service/http and link
                // http_steps, whose ignore predicate differs.
                let is_http = target
                    .src_path
                    .to_string_lossy()
                    .contains("behaviour/service/http");
                let source = if is_http { &by_feature_http } else { &by_feature };
                let Some(list) = source.get(feature) else {
                    bail!(
                        "target {target_id} declares behaviour data {feature}, which is not in \
                         the pinned corpus at {}",
                        inputs.behaviour_root.display()
                    );
                };
                // A scenario name is not unique within a feature file. `relationtype.feature`
                // declares "Relation type cannot unset ordering if @distinct annotation is
                // set" at both L3008 and L3036, and Cucumber runs both. Keying the leaf id
                // on the name alone collapsed them into one, so the catalogue under-counted
                // and the second run of each name came back as an uncatalogued case.
                // Disambiguating by line keeps the id stable across runs and distinct per
                // declaration.
                // Disambiguate on the whole (name, example row) key, not the name alone.
                // `define.feature` declares three *different* `Scenario Outline`s all called
                // "cannot define different annotations of the same category on owns"
                // (L1608, L1810, L1905), each with its own Examples rows — so row 1 of each
                // collided, the catalogue under-counted, and Cucumber's extra runs came back
                // as uncatalogued cases. The declaration line separates them and is stable
                // across runs.
                let mut seen: BTreeMap<(&str, usize), usize> = BTreeMap::new();
                for s in list {
                    if s.no_example_rows {
                        exclusions.push(Exclusion {
                            subject_id: format!("{target_id}::{}::{}", feature, s.name),
                            predicate: "generates_no_cases".into(),
                            reason: format!(
                                "Scenario Outline at {}:{} has an Examples header but no data \
                                 rows (all commented out upstream), so Cucumber generates zero \
                                 scenarios for it",
                                s.feature_path, s.line
                            ),
                            owner: "upstream".into(),
                            expiry: "2027-01-01".into(),
                            replacement_test_id: None,
                        });
                        continue;
                    }
                    let occurrence = seen.entry((s.name.as_str(), s.example_row)).or_default();
                    *occurrence += 1;
                    let row = if s.example_row > 0 { format!("#{}", s.example_row) } else { String::new() };
                    let suffix = if *occurrence == 1 {
                        row
                    } else {
                        format!("{row}@{}", s.line)
                    };
                    leaf_cases.push(LeafCase {
                        leaf_case_id: format!("{target_id}::{}::{}{}", feature, s.name, suffix),
                        target_id: target_id.clone(),
                        kind: LeafKind::Cucumber,
                        display_name: Some(s.name.clone()),
                        source_hash: sha256_str(&format!("{}:{}:{}", s.feature_path, s.line, s.name)),
                        declared_ignored: s.ignored,
                        resource_group: Some("server-port".into()),
                    });
                }
            }
        } else if is_failpoint {
            let registry = failpoints::parse_registry(&std::fs::read_to_string(
                inputs.fork_root.join("common/fail_point/lib.rs"),
            )?)?;
            let contexts = failpoints::parse_loop_contexts(&std::fs::read_to_string(&target.src_path)?)?;
            for case in failpoints::expand(&registry, &contexts) {
                leaf_cases.push(LeafCase {
                    leaf_case_id: format!(
                        "{target_id}::{}::{}",
                        case.loop_context, case.fail_point
                    ),
                    target_id: target_id.clone(),
                    kind: LeafKind::Failpoint,
                    display_name: Some(format!("{}[{}]", case.loop_context, case.fail_point)),
                    source_hash: sha256_str(&format!("{}:{}", case.loop_context, case.fail_point)),
                    declared_ignored: false,
                    resource_group: Some("server-port".into()),
                });
            }
        } else if is_bench {
            leaf_cases.push(LeafCase {
                leaf_case_id: format!("{target_id}::harness"),
                target_id: target_id.clone(),
                kind: LeafKind::Script,
                display_name: Some(format!("criterion harness {}", target.name)),
                source_hash: sha256_str(&src_rel),
                declared_ignored: false,
                resource_group: Some("bench".into()),
            });
        }
        // LIBTEST_LIST targets get their leaf cases from `--list` on the built harness,
        // which requires a build; `enrich_libtest_cases` fills them in afterwards.
    }

    // --- Bazel-macro test targets that Cargo cannot express at all.
    //
    // `release_validate_deps` expands to two Bazel test targets, both Kotlin/JVM. Upstream
    // tags the call site `manual` so `bazel test //...` skips it, but brief §22.2 counts
    // release/dependency validations in the denominator, so it is catalogued and ported
    // rather than dropped.
    for bt in build_targets.iter().filter(|b| b.rule == "release_validate_deps") {
        let name = bt.label.rsplit(':').next().unwrap_or_default();
        let standard = {
            let mut c = name.replace('-', "_");
            if let Some(first) = c.get_mut(0..1) {
                first.make_ascii_uppercase();
            }
            c
        };
        for (suffix, expansion) in [
            (format!("{standard}_gen"), "_release_validate_deps_script_test (rule, test = True)"),
            (name.to_string(), "kt_jvm_test"),
        ] {
            let target_id = format!("bazel-macro::{}:{suffix}", bt.build_file.trim_end_matches("BUILD").trim_end_matches('/'));
            targets.push(Target {
                target_id: target_id.clone(),
                origin: Origin::BazelMacro,
                upstream_label: Some(format!("//:{suffix}")),
                cargo_package: None,
                cargo_target: None,
                source_files: vec![HashedFile {
                    path: bt.build_file.clone(),
                    sha256: sha256_file(&inputs.fork_root.join(&bt.build_file))?,
                }],
                case_discovery: CaseDiscovery::StaticCheck,
                platform_predicate: "any".into(),
                features: Vec::new(),
                cfg: Vec::new(),
                env: BTreeMap::new(),
                fixture_ids: Vec::new(),
                working_directory: Some(".".into()),
                timeout_seconds: 300,
                serial_group: None,
                // The Kotlin harness is replaced by an equivalent Rust check over the same
                // inputs (workspace refs vs VERSION vs the tagged deps).
                port_status: PortStatus::SemanticPort,
            });
            leaf_cases.push(LeafCase {
                leaf_case_id: format!("{target_id}::validate-tagged-deps"),
                target_id,
                kind: LeafKind::StaticCheck,
                display_name: Some(format!("{expansion}: {}", bt.attr_summary())),
                source_hash: sha256_str(&format!("{}:{suffix}", bt.label)),
                declared_ignored: bt.tags.iter().any(|t| t == "manual"),
                resource_group: None,
            });
        }
    }

    // --- Static checks declared only in BUILD (rustfmt / checkstyle).
    for bt in &build_targets {
        if bt.rule == "rust_test" || bt.rule == "release_validate_deps" {
            continue;
        }
        let target_id = format!("static::{}", bt.label);
        targets.push(Target {
            target_id: target_id.clone(),
            origin: Origin::BazelDirect,
            upstream_label: Some(bt.label.clone()),
            cargo_package: None,
            cargo_target: None,
            source_files: vec![HashedFile {
                path: bt.build_file.clone(),
                sha256: sha256_file(&inputs.fork_root.join(&bt.build_file))?,
            }],
            case_discovery: CaseDiscovery::StaticCheck,
            platform_predicate: "any".into(),
            features: Vec::new(),
            cfg: Vec::new(),
            env: BTreeMap::new(),
            fixture_ids: Vec::new(),
            working_directory: Some(".".into()),
            timeout_seconds: 900,
            serial_group: None,
            port_status: PortStatus::SemanticPort,
        });
        leaf_cases.push(LeafCase {
            leaf_case_id: format!("{target_id}::check"),
            target_id,
            kind: LeafKind::StaticCheck,
            display_name: Some(bt.rule.clone()),
            source_hash: sha256_str(&bt.label),
            declared_ignored: false,
            resource_group: None,
        });
    }

    // --- Shell-origin targets that Bazel never declared as tests but upstream runs.
    let crash_script = inputs.fork_root.join("tool/test/simulate-crash.sh");
    if crash_script.exists() {
        let target_id = "shell::tool/test/simulate-crash.sh".to_string();
        targets.push(Target {
            target_id: target_id.clone(),
            origin: Origin::Shell,
            upstream_label: None,
            cargo_package: None,
            cargo_target: None,
            source_files: vec![HashedFile {
                path: "tool/test/simulate-crash.sh".into(),
                sha256: sha256_file(&crash_script)?,
            }],
            case_discovery: CaseDiscovery::Script,
            platform_predicate: "linux-x86_64+docker".into(),
            features: Vec::new(),
            cfg: Vec::new(),
            env: BTreeMap::new(),
            fixture_ids: vec!["typedb-assembly-archive".into()],
            working_directory: Some(".".into()),
            timeout_seconds: 3600,
            serial_group: Some("docker".into()),
            // Ported to a Rust xtask preserving kill points (brief Appendix E.3-19).
            port_status: PortStatus::SemanticPort,
        });
        // Not a leaf case: it cannot run here, and a case that cannot run is an exclusion,
        // not a permanent red. `tool/test/simulate-crash.sh` needs Docker, the Bazel-built
        // image `bazel:assemble-linux-x86_64` (blocked on TB-BASE) and TypeDB Console
        // (blocked on TCONSOLE), and it loops for 10 minutes by design. No BUILD rule and no
        // Rust source references it, so upstream does not run it in CI either — it is a
        // developer utility. The target stays in the catalogue so the obligation is visible.
        exclusions.push(Exclusion {
            subject_id: format!("{target_id}::crash-restart-loop"),
            predicate: "blocked_on_unresolved_input".into(),
            reason: "requires Docker plus the Bazel-built OCI image (TB-BASE, unresolved) and \
                     TypeDB Console (TCONSOLE, unresolved); declared by no BUILD rule or Rust \
                     source, so upstream CI does not run it either"
                .into(),
            owner: "programme".into(),
            expiry: "2027-01-01".into(),
            replacement_test_id: None,
        });
    }

    // --- Upstream's own declared skips (Cucumber only at this point; see the note below).
    //
    // A scenario its harness filters out is counted, never passed (§22.3), but the verdict
    // also requires each to carry an exclusion naming who owns it. The owner is upstream:
    // these are `@ignore` / `@ignore-typedb` / `@ignore-typedb-http` tags in the pinned
    // behaviour corpus, and which of them applies depends on the harness (CR-A-09). The
    // fork does not get to un-skip them, so the entry records the fact rather than claiming
    // a plan to fix it.
    for case in leaf_cases.iter().filter(|c| c.declared_ignored) {
        exclusions.push(Exclusion {
            subject_id: case.leaf_case_id.clone(),
            predicate: "declared_ignored_upstream".into(),
            reason: "tagged @ignore / @ignore-typedb / @ignore-typedb-http in the pinned \
                     behaviour corpus; the harness's own filter_run predicate drops it before \
                     reporting"
                .into(),
            owner: "upstream".into(),
            expiry: "2027-01-01".into(),
            replacement_test_id: None,
        });
    }

    // --- Targets blocked on unresolved distribution artifacts.
    //
    // `tests/assembly/*` and `test_fail_points` extract $TYPEDB_ASSEMBLY_ARCHIVE and then
    // drive the server with `typedb console`. That archive is Bazel's `package-typedb-all`
    // = server + console-repackaged + loader-repackaged (root BUILD L182-188), so it cannot
    // be produced without TypeDB Console and Loader — both class-U nodes with no URL,
    // checksum or licence recorded. Building only the server does not help: the test uses
    // Console to run its script.
    //
    // These stay leaf cases and are expected to FAIL rather than be skipped, because "did
    // not run" and "passed" must never look alike. The exclusion records why, so the red is
    // owned and traceable to a named unresolved input instead of unexplained.
    for target in targets.iter().filter(|t| {
        t.env.contains_key("TYPEDB_ASSEMBLY_ARCHIVE")
            || t.fixture_ids.iter().any(|f| f == "typedb-assembly-archive")
    }) {
        exclusions.push(Exclusion {
            subject_id: target.target_id.clone(),
            predicate: "blocked_on_unresolved_input".into(),
            reason: "packaging test: extracts $TYPEDB_ASSEMBLY_ARCHIVE and drives the server \
                     with `typedb console --script=…`. Blocked only on TCONSOLE — the Console \
                     CLI is a released binary used here as a test *client*, not a component \
                     under change, and needs only a pinned URL + SHA-256. TLOADER is bundled \
                     in the same archive but referenced by no test (0 occurrences under \
                     tests/), so it blocks nothing. Nothing about the storage backend depends \
                     on either."
                .into(),
            owner: "programme".into(),
            expiry: "2027-01-01".into(),
            replacement_test_id: None,
        });
    }

    // --- Reconciliation.
    for bt in &build_targets {
        if bt.rule == "rust_test" && !matched_build.contains(&bt.label) {
            recon.build_only.push(bt.label.clone());
        }
    }
    recon.matched = matched_build.into_iter().collect();
    for t in &targets {
        if t.origin != Origin::Cargo || t.upstream_label.is_some() {
            continue;
        }
        // A lib target with no BUILD wrapper is Cargo running more than Bazel did.
        if t.case_discovery == CaseDiscovery::LibtestList
            && t.cargo_package.as_deref() == t.cargo_target.as_deref()
        {
            recon.cargo_only_lib_units.push(t.target_id.clone());
        } else {
            recon.cargo_only.push(t.target_id.clone());
        }

        // Explain it against whatever BUILD rule declares the same name.
        let name = t.cargo_target.clone().unwrap_or_default();
        let explanation = match recon.declared_names.get(&name) {
            Some(decl) => format!("upstream declares {decl}, which produces no test target"),
            None => "no BUILD rule of any kind declares this name: Cargo auto-discovers the \
                     source file, Bazel never builds or runs it"
                .to_string(),
        };
        recon.cargo_only_explained.insert(t.target_id.clone(), explanation);
    }

    // --- Fixtures that are still unresolved are recorded as exclusions, not omitted.
    exclusions.push(Exclusion {
        subject_id: "typedb-console".into(),
        predicate: "fixture_unresolved".into(),
        reason: "TypeDB Console 3.12.0 linux-x86_64 URL/SHA-256/licence unresolved at G0 \
                 (sources/UNRESOLVED.md); assembly and failpoint suites cannot be staged until \
                 it is pinned."
            .into(),
        owner: "implementation-agent".into(),
        expiry: "2026-12-31".into(),
        replacement_test_id: None,
    });

    targets.sort_by(|a, b| a.target_id.cmp(&b.target_id));
    leaf_cases.sort_by(|a, b| a.leaf_case_id.cmp(&b.leaf_case_id));

    // Required (case, profile) pairs: U0 and U1 must run the identical applicable
    // corpus, so every leaf case is required under both (brief §22.4).
    let required_pairs = leaf_cases
        .iter()
        .flat_map(|c| {
            [ProfileId::U0, ProfileId::U1].into_iter().map(move |p| RequiredPair {
                leaf_case_id: c.leaf_case_id.clone(),
                profile_id: p,
                reason: Some("U0/U1 structured equality (addendum A17.4b)".into()),
            })
        })
        .collect();

    Ok(CatalogOutput {
        catalog: Catalog {
            schema_version: 1,
            source_lock_digest: inputs.source_lock_digest.clone(),
            rust_toolchain: RustToolchain {
                rustc: inputs.rustc.clone(),
                cargo: inputs.cargo.clone(),
                native_toolchain_digest: inputs.native_toolchain_digest.clone(),
            },
            target_triple: inputs.target_triple.clone(),
            bazel_query_oracle: None,
            profiles: default_profiles(),
            targets,
            leaf_cases,
            required_pairs,
            fixtures,
            exclusions,
        },
        reconciliation: recon,
        build_targets,
    })
}

/// Add libtest leaf cases discovered by running `--list` on built harnesses.
///
/// Kept separate from [`generate`] so the catalogue's structure can be produced without a
/// build, while the leaf-case count still comes from the real harness rather than a
/// source-text guess.
/// Give every declared-ignored leaf case an exclusion naming its owner.
///
/// Must run *after* `enrich_libtest_cases`, because a libtest `#[ignore]` is invisible until
/// the harness is queried with `--list --ignored`: plain `--list` reports every test as
/// `name: test`. Generating exclusions during `generate()` alone therefore missed them, and
/// the gate correctly reported one declared skip with no entry.
pub fn add_declared_ignored_exclusions(catalog: &mut model::Catalog) {
    let existing: BTreeSet<String> =
        catalog.exclusions.iter().map(|e| e.subject_id.clone()).collect();
    let new: Vec<Exclusion> = catalog
        .leaf_cases
        .iter()
        .filter(|c| c.declared_ignored && !existing.contains(&c.leaf_case_id))
        .map(|c| Exclusion {
            subject_id: c.leaf_case_id.clone(),
            predicate: "declared_ignored_upstream".into(),
            reason: "disabled upstream in the pinned source — an `#[ignore]` attribute or an \
                     @ignore-family tag; the fork does not get to un-skip it"
                .into(),
            owner: "upstream".into(),
            expiry: "2027-01-01".into(),
            replacement_test_id: None,
        })
        .collect();
    catalog.exclusions.extend(new);
    catalog.exclusions.sort_by(|a, b| a.subject_id.cmp(&b.subject_id));
    catalog.exclusions.dedup_by(|a, b| a.subject_id == b.subject_id);
}

pub fn enrich_libtest_cases(
    catalog: &mut Catalog,
    listings: &BTreeMap<String, Vec<LibtestCase>>,
) -> Result<()> {
    for (target_id, cases) in listings {
        let Some(target) = catalog.targets.iter().find(|t| &t.target_id == target_id) else {
            bail!("libtest listing for unknown target {target_id}");
        };
        if target.case_discovery != CaseDiscovery::LibtestList {
            continue;
        }
        for case in cases {
            catalog.leaf_cases.push(LeafCase {
                leaf_case_id: format!("{target_id}::{}", case.name),
                target_id: target_id.clone(),
                kind: LeafKind::Libtest,
                display_name: Some(case.name.clone()),
                source_hash: sha256_str(&format!("{target_id}:{}", case.name)),
                declared_ignored: case.ignored,
                resource_group: None,
            });
        }
    }
    catalog.leaf_cases.sort_by(|a, b| a.leaf_case_id.cmp(&b.leaf_case_id));
    catalog.leaf_cases.dedup_by(|a, b| a.leaf_case_id == b.leaf_case_id);
    Ok(())
}

/// One entry of a `--list --format terse` listing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LibtestCase {
    pub name: String,
    pub ignored: bool,
}

/// Parse `<binary> --list --format terse` output.
///
/// libtest prints `name: test` and `name: test` with a trailing `#[ignore]` marker under
/// `--format terse`; the pretty format is not accepted, because its summary lines are easy
/// to miscount.
pub fn parse_libtest_list(stdout: &str) -> Result<Vec<LibtestCase>> {
    let mut out = Vec::new();
    for line in stdout.lines() {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        // Trailing summary line, e.g. "12 tests, 0 benchmarks".
        if line.ends_with(" tests, 0 benchmarks")
            || (line.contains(" test") && line.contains(", ") && line.contains("benchmark"))
        {
            continue;
        }
        let Some((name, kind)) = line.rsplit_once(": ") else {
            bail!("unparseable libtest listing line {line:?}");
        };
        match kind.trim() {
            "test" => out.push(LibtestCase { name: name.to_string(), ignored: false }),
            "test (ignored)" => out.push(LibtestCase { name: name.to_string(), ignored: true }),
            "benchmark" => out.push(LibtestCase { name: name.to_string(), ignored: false }),
            other => bail!("unknown libtest case kind {other:?} in line {line:?}"),
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_a_terse_listing_including_ignored_cases() {
        let cases = parse_libtest_list(
            "storage::tests::put_get: test\nstorage::tests::slow: test (ignored)\n2 tests, 0 benchmarks\n",
        )
        .unwrap();
        assert_eq!(cases.len(), 2);
        assert!(!cases[0].ignored);
        assert!(cases[1].ignored, "ignored cases stay in the denominator");
    }

    #[test]
    fn refuses_to_silently_drop_an_unreadable_line() {
        assert!(parse_libtest_list("garbage line without a kind\n").is_err());
    }

    #[test]
    fn maps_behaviour_data_labels_to_corpus_paths() {
        let paths = feature_paths_from_data(&[
            "@typedb_behaviour//connection:database.feature".to_string(),
            "//tests/behaviour:script.tql".to_string(),
        ]);
        assert_eq!(paths, vec!["connection/database.feature"]);
    }
}
