//! Catalogue data model — the Rust mirror of
//! `contract/typedb-r2-v14-upstream-test-catalog.schema.json`.
//!
//! Field names and enum spellings are the schema's, so the emitted JSON validates
//! against the contract schema without a translation layer.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum ProfileId {
    U0,
    U1,
    U2,
    U3,
    U4,
}

impl ProfileId {
    pub const ALL: [ProfileId; 5] = [
        ProfileId::U0,
        ProfileId::U1,
        ProfileId::U2,
        ProfileId::U3,
        ProfileId::U4,
    ];
}

impl std::fmt::Display for ProfileId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ProfileId::U0 => "U0",
            ProfileId::U1 => "U1",
            ProfileId::U2 => "U2",
            ProfileId::U3 => "U3",
            ProfileId::U4 => "U4",
        })
    }
}

impl std::str::FromStr for ProfileId {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "U0" => Ok(ProfileId::U0),
            "U1" => Ok(ProfileId::U1),
            "U2" => Ok(ProfileId::U2),
            "U3" => Ok(ProfileId::U3),
            "U4" => Ok(ProfileId::U4),
            other => anyhow::bail!("unknown profile {other}; expected U0..U4"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    pub profile_id: ProfileId,
    pub kv_backend: String,
    pub durability: String,
    pub object_store: String,
    pub controller: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub features: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cfg: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config_digest: Option<String>,
}

/// Where a target was declared. `CARGO` alone is not trusted: the pinned root manifest
/// is generated by a Bazel-invoking sync tool, so BUILD-declared targets are enumerated
/// independently and reconciled (brief §22.2, §21.10).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Origin {
    Cargo,
    BazelDirect,
    BazelMacro,
    Shell,
    StaticCheck,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CaseDiscovery {
    LibtestList,
    CucumberScenarios,
    FailpointRegistry,
    Script,
    StaticCheck,
}

/// How faithfully a target survives the move off Bazel (brief §22.5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PortStatus {
    /// Source unchanged, runs as-is.
    ByteIdentical,
    /// Source unchanged; the runner stages fixtures/env/cwd that Bazel used to provide.
    LauncherAdapted,
    /// Source edited; requires a `TestPortRecord`.
    SemanticPort,
    /// Counted in the denominator, not executed; requires an `exclusion` entry.
    Excluded,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashedFile {
    pub path: String,
    pub sha256: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Target {
    pub target_id: String,
    pub origin: Origin,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upstream_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cargo_package: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cargo_target: Option<String>,
    pub source_files: Vec<HashedFile>,
    pub case_discovery: CaseDiscovery,
    pub platform_predicate: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub features: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cfg: Vec<String>,
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub env: std::collections::BTreeMap<String, String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub fixture_ids: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_directory: Option<String>,
    pub timeout_seconds: u64,
    /// Required by the schema even when null, so it is never elided.
    #[serde(default)]
    pub serial_group: Option<String>,
    pub port_status: PortStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum LeafKind {
    Libtest,
    Cucumber,
    Failpoint,
    Script,
    StaticCheck,
}

/// One executable unit of the denominator. A composite harness that loops over N
/// scenarios contributes N leaf cases, never one opaque green (brief §22.2).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeafCase {
    pub leaf_case_id: String,
    pub target_id: String,
    pub kind: LeafKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    pub source_hash: String,
    pub declared_ignored: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_group: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FixtureKind {
    File,
    Directory,
    Binary,
    Archive,
    Generated,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Fixture {
    pub fixture_id: String,
    pub kind: FixtureKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    pub sha256: String,
    pub licence: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequiredPair {
    pub leaf_case_id: String,
    pub profile_id: ProfileId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// An owned, dated, justified hole in the denominator. Exclusions stay visible;
/// they are never removed from the count (brief §22.3).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Exclusion {
    pub subject_id: String,
    pub predicate: String,
    pub reason: String,
    pub owner: String,
    /// ISO-8601 date; an expired exclusion fails the catalogue.
    pub expiry: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replacement_test_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RustToolchain {
    pub rustc: String,
    pub cargo: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native_toolchain_digest: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BazelQueryOracle {
    pub digest: String,
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Catalog {
    pub schema_version: u32,
    pub source_lock_digest: String,
    pub rust_toolchain: RustToolchain,
    pub target_triple: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bazel_query_oracle: Option<BazelQueryOracle>,
    pub profiles: Vec<Profile>,
    pub targets: Vec<Target>,
    pub leaf_cases: Vec<LeafCase>,
    pub required_pairs: Vec<RequiredPair>,
    pub fixtures: Vec<Fixture>,
    pub exclusions: Vec<Exclusion>,
}

/// The five execution profiles of the conformance plan (brief §22.4).
pub fn default_profiles() -> Vec<Profile> {
    let p = |id, kv: &str, dur: &str, obj: &str, ctrl: &str| Profile {
        profile_id: id,
        kv_backend: kv.into(),
        durability: dur.into(),
        object_store: obj.into(),
        controller: ctrl.into(),
        features: Vec::new(),
        cfg: Vec::new(),
        config_digest: None,
    };
    vec![
        p(ProfileId::U0, "rocksdb-pristine", "file-wal", "none", "upstream-local"),
        p(ProfileId::U1, "rocksdb-adapter", "file-wal", "none", "fork-local"),
        p(ProfileId::U2, "slatedb-localfs", "file-wal", "localfs", "fork-local"),
        p(ProfileId::U3, "slatedb-localfs", "remote-wal", "localfs", "deterministic-model"),
        p(ProfileId::U4, "slatedb-r2", "remote-wal", "r2", "real-durable-object"),
    ]
}
