/*
 * R5-SEC-03: the ISSUER SIDE of the capability protocol — the only module
 * that mints tokens.
 *
 * Minting requires an Ed25519 PRIVATE key (PKCS#8). Who holds one:
 *
 *   local-dev posture     the committed INSECURE dev seeds (key-config.ts),
 *                         resolved into the runtime ONLY under the
 *                         "local-dev" profile so the dev-lane in-worker
 *                         issuance route (/capability) can sign;
 *   managed local runs    per-run ephemeral keypairs generated by the boot
 *                         scripts (scripts/issuer.mjs) — private halves
 *                         never leave the script process;
 *   production            a provisioned private issuer service (R5-SEC-02
 *                         follow-up); the runtime is NEVER it.
 *
 * A managed runtime resolves NO private key (key-config.ts resolves only
 * public verification keyrings + the journal secret), so importing this
 * module cannot make a managed worker/DO an issuer: there is nothing for
 * it to sign with. That structural fact — not code review — is what the
 * "stolen managed env vars cannot mint" mutant tests pin down.
 */

import { hex } from "./journal-crypto.ts";
import { ed25519Sign } from "./ed25519.ts";
import {
  base64urlEncode, capabilityBodyBytes, CAPABILITY_TOKEN_ALG, CAPABILITY_TOKEN_VERSION,
  isKnownCapabilityMethod, REQUIRED_RESTRICTIONS,
  type CapabilityPayload,
} from "./capability.ts";
import { provisionKid, type ProvisionBinding } from "./registry.ts";

/** Sign a fully-formed v3 payload. The payload's `v`/`alg` must be the
 *  current schema (the issuer refuses to sign anything it would itself not
 *  verify); the kid names the signing key and travels inside the signed
 *  body. */
export async function mintCapabilityToken(
  signingKeyPkcs8: Uint8Array, payload: CapabilityPayload,
): Promise<string> {
  if (payload.v !== CAPABILITY_TOKEN_VERSION || payload.alg !== CAPABILITY_TOKEN_ALG) {
    throw new Error("ISSUER_SCHEMA_MISMATCH: refusing to sign a non-v3/non-Ed25519 payload");
  }
  if (!isKnownCapabilityMethod(payload.method)) {
    throw new Error(`CAPABILITY_METHOD_UNKNOWN: ${payload.method}`);
  }
  // issuance is fail-closed on the same restriction table verification
  // enforces: a token missing a mandatory restriction is never produced,
  // so the two ends cannot disagree about what may stay unbound
  for (const required of REQUIRED_RESTRICTIONS[payload.method] ?? []) {
    if (payload[required] === undefined) {
      throw new Error(`CAPABILITY_RESTRICTION_MISSING: ${payload.method} requires ${required}`);
    }
  }
  const body = capabilityBodyBytes(payload);
  const signature = await ed25519Sign(signingKeyPkcs8, body);
  return `${base64urlEncode(body)}.${hex(signature)}`;
}

/**
 * Mint the internal PROVISION capability (issuer side; tests and the local
 * managed stack mint it in-process from the run's ephemeral provisioning
 * keypair). It is a schema-v3 token under the PROVISION scope key: the
 * binding rides in the token's env/tenantId/databaseId fields, so the
 * Worker's frame check and the DO's authoritative check reuse the one
 * token verifier.
 */
export async function mintProvisionToken(
  provisionSigningKeyPkcs8: Uint8Array,
  binding: ProvisionBinding,
  options: { nonce: string; expiresAtMs: number; principal?: string; kid?: string },
): Promise<string> {
  const payload: CapabilityPayload = {
    v: CAPABILITY_TOKEN_VERSION,
    alg: CAPABILITY_TOKEN_ALG,
    kid: options.kid ?? provisionKid(binding.environment),
    env: binding.environment,
    tenantId: binding.tenantId,
    principal: options.principal ?? "provisioner",
    databaseId: binding.databaseId,
    method: "PROVISION",
    // provisioning happens before any controller incarnation is relevant
    // (the DO may not even exist); the incarnation field is fixed at 0 and
    // deliberately NOT checked for PROVISION (see verifyProvisionToken).
    incarnation: 0,
    nonce: options.nonce,
    expiresAtMs: options.expiresAtMs,
  };
  return mintCapabilityToken(provisionSigningKeyPkcs8, payload);
}
