#!/usr/bin/env python3
"""Render the human gate table from the machine ledger (docs/ledger/gates.json).

The ledger is the single source of truth; the block between the markers in
docs/operations.md is GENERATED and must never be hand-edited. lint_ledger.py
fails when the rendered block drifts from the ledger, so a status change is a
ledger change first.
"""

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
LEDGER = REPO / "docs" / "ledger" / "gates.json"
OPERATIONS = REPO / "docs" / "operations.md"
BEGIN = "<!-- ledger-gate-table:begin (generated by tools/ledger/render_status.py; edit docs/ledger/gates.json instead) -->"
END = "<!-- ledger-gate-table:end -->"


def render() -> str:
    ledger = json.loads(LEDGER.read_text())
    current = ledger["current"]
    lines = [BEGIN, ""]
    # R8-P0-02: the current-fact block comes FIRST, and every number in it is
    # read from the ledger's one canonical section — never restated in prose.
    cov, mq, drv = current["coverage"], current["mode_q"], current["drivers"]
    lines.append(
        f"**Current state at `{current['as_of_commit'][:12]}`** (generated; "
        f"re-derived by `{current['derived_by']}`)"
    )
    lines.append("")
    lines.append("| Fact | Value | Derived from |")
    lines.append("|---|---|---|")
    lines.append(
        f"| Qualification coverage | {cov['covered']:,} covered / {cov['partial']:,} partial / "
        f"{cov['uncovered']:,} uncovered of {cov['total']:,} rows | `{cov['derived_by']}` |"
    )
    lines.append(f"| | _{cov['meaning']}_ | |")
    lines.append(
        f"| Mode-Q | {mq['state']}, {mq['targets']} configured test targets, root "
        f"`{mq['bundle_root'][:16]}…` ({mq['bazel_version']}) | `{mq['derived_by']}` |"
    )
    lines.append(
        f"| Official driver rows | {drv['covered']} covered / {drv['partial']} partial of "
        f"{drv['total']} | `{drv['evidence']}` |"
    )
    lines.append("")
    lines.append("| Gate / lane | State | Why |")
    lines.append("|---|---|---|")
    for g in ledger["gates"]:
        row = current["gates"][g["id"]]
        blockers = row.get("blocking_findings", []) + row.get("blockers", [])
        remaining = ("<br>Remaining: " + "; ".join(blockers)) if blockers else ""
        lines.append(f"| **{g['id']}** {g['title']} | **{row['state']}** | {g['why']}{remaining} |")
    for lane in ledger["lanes"]:
        lines.append(f"| {lane['id']} | **{lane['state']}** | {lane['why']} |")
    lines.append("")
    lines.append(
        f"Adopted audit: {ledger['adopted_audit']['directive']} at "
        f"`{ledger['adopted_audit']['audited_commit'][:12]}` — decision: "
        f"{ledger['adopted_audit']['decision']}."
    )
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def inject() -> int:
    text = OPERATIONS.read_text()
    if BEGIN not in text or END not in text:
        print("operations.md is missing the ledger markers", file=sys.stderr)
        return 1
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    OPERATIONS.write_text(head + render() + tail)
    print("rendered gate table into docs/operations.md")
    return 0


if __name__ == "__main__":
    if "--print" in sys.argv:
        print(render())
        sys.exit(0)
    sys.exit(inject())
